### ISSUE TITLE
🐛 Android client drops frames when playing 4K HEVC video

### ISSUE THREAD

**Issue by nyanmisaka** [DonutWare/Fladder#117]
### Description

Frame drops when playing 4K HEVC video directly with hardware acceleration on Android client, video is common SDR 4k 23.98fps. Although hardware accelerated decoding is enabled it does not seem to work.

The device is powered by Snapdragon 835, which is not the latest but capable of decoding 4K HEVC and VP9 videos. Using other video players such as VLC and Chrome can play 4K HEVC videos smoothly.

### Reproduction steps

1. Play any HEVC-encoded 4K (3840x2160) video on capable Android device
2. You can see that the video obviously drops frames
3. It seems that hardware decoding is not taking effect

### Logs

Is there a way to show whether the player on Android is using a hardware decoder or FFmpeg's software decoder?

### Platform

Android

### App Version

v0.4.1

**Comment by PartyDonut** [comment]
No log anywhere except when debugging unfortunately. However if the toggle is set to hardware accelerated it should do just that.

AndroidTV was unbearable slow as well. 

I've created a feature ticket to investigate on possible ways to fix this issue. I'll close this one so we can keep issue about the media player in there.

Move to here #122

Thanks for reporting the bug.
