### ISSUE TITLE
🐛 Progress report causes to thread pool starvation on server side

### ISSUE THREAD

**Issue by lmgarret** [DonutWare/Fladder#121]
### Description

Hi! This is a bug I've only found now, I've mostly been using the app to play content offline.

While playing some TV show episode, the Jellyfin server became unresponsive. I could see on the server that the count of jellyfin ffmpeg threads went from ~20-30 to serveral hundreds.

I wrote this quick script to monitor the number of ffmpeg threads on the server, polling it every 5s

```bash
#!/bin/bash

while true; do
	current_time=$(date +"%Y-%m-%d %H:%M:%S")
	count=$(pgrep -wf ffmpeg | wc -l)
	echo "$current_time: $count"
	sleep 5
done
```

The jellyfin server logs show:

```log
[2024-11-04 09:46:10.079 +00:00] [WRN] As of "11/04/2024 09:46:08 +00:00", the heartbeat has been running for "00:00:01.2073446" which is longer than "00:00:01". This could be caused by thread pool starvation.
```

### Reproduction steps

1. On the server sidem, run the shared script above to monitor the number of ffmpeg threads started
2. Play an episode of a TV show with a lot of episodes (around 170 in my case)
3. Monitor the number of threads, which should quickly rise, around 10 per sec in my case. The server may eventually crash

See `Other notes` below for more investigation details which brought me to these reproduction steps

### Screenshots

![DESCRIPTION](LINK.png)

## Other notes
I initially got the issue while running the Linux app. To investigate the API calls being made, I ran the web version and got the same issue. I tried streaming the same episode using the Jellyfin web interface and the official Jellyfin Media Player and did not run in this issue.

Inspecting the API calls, I noticed that:

1. Fladder calls `POST /Sessions/Playing/Progress` every 1.5s when the offical frontend do it every ~10s
2. Fladder sends a pretty big (170+ in that case) `NowPlayingQueue` list when reporting progress, whereas the official frontend does not send any?

Point 1. sure seems convenient, having a better granular progress tracking (although resuming an episode to max 10s before you stopped watching it can actually be a good feature). But point 2. a.k.a. the big `NowPlayingQueue` looks suspicious. I then tried to

2. 1. Play an episode in a TV show with way less episodes in total. The `NowPlayingQueue` had around ~50 elements, and I did not run into the same issue.
2. 2. Patched the code heartbeat
https://github.com/DonutWare/Fladder/blob/043e465058ae8c65df522f2c98da089ea5956b91/lib/models/playback/transcode_playback_model.dart#L65-L66
and here
https://github.com/DonutWare/Fladder/blob/043e465058ae8c65df522f2c98da089ea5956b91/lib/models/playback/direct_playback_model.dart#L65-L66

to return `[]`. It doesn't trigger the bug as well (although not a fix)

### Platform

Linux, Web

### App Version

v0.4.1

**Comment by PartyDonut** [comment]
Thanks for the very detailed bug report, great that you also found the issue already!

For the report back seconds, while that was my original intention to have a smaller report rate 10 seconds would be just fine. 

For the NowPlayingQueue, the best option would probably be to just leave it out. There was no real reason behind sending it I dont think Jellyfin even does anything with that data? The app also keeps and uses the NowPlayingQueue internally so nothing would change in Fladder.

I'll try to have a look later this week given that it's a pretty big bug (though easy to fix).

**Comment by lmgarret** [comment]
Thanks for the quick response!

> There was no real reason behind sending it I dont think Jellyfin even does anything with that data?

Yeah since the web client does not even send the field, I'd assume it's not even necessary for the `Next up` banner. But I haven't digged too much into this.

I'll be using a hotfixed version removing the `nowPlayingQueue` from the post payloads in the next few days, I'll report back if I run into anything funky.
