### ISSUE TITLE
Improving visiblity of Episode banners in the details view

### ISSUE THREAD

**Issue by PartyDonut** [DonutWare/Fladder#127]
@alexq83 #120 

Here are 2 screenshots showing emby and Fladder in the episode view in portrait. 

<img src="https://github.com/user-attachments/assets/d4842f8d-bd1c-49cf-8edc-582e39416e8e" width=45% height=45%>
<img src="https://github.com/user-attachments/assets/7bc7272f-f003-4185-b266-db5187ce8026" width=45% height=45%>

**Comment by alexq83** [comment]
@PartyDonut I promised you some more screenshots and a couple of thoughts. These are from the tv versions of the emby (universal) app and plex, but I think they would also work for tablets in landscape (phones not so much)

![Image](https://github.com/user-attachments/assets/bb616d83-8c5b-41ba-80a0-bece2a1846a0)

**Comment by PartyDonut** [comment]
Thanks for the update!

I'll take it into account.
When I first designed this there was no blurred images support in Fladder. However that's now enabled so I should be able to play around more with this and better align the posters without upscaling small images.

**Comment by Shah-do** [comment]
for the mobile UI I think the UI of the new Plex Preview app can be great inspiration.
![Image](https://github.com/user-attachments/assets/9fe2f097-8778-4a29-ad11-7faa823b4dd1)
