### ISSUE TITLE
please update the latest version on play store as well

### ISSUE THREAD

**Issue by Gujjugaming2k** [DonutWare/Fladder#152]
### Description

please update the latest version on play store as well

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash

```

### Platform

Android

**Comment by PartyDonut** [comment]
Please refrain from making multiple discussion/tickets. Also this is for bug reports not for issues outside of the app itself.

Apk's are always uploaded to the Playstore. When/if google approves the apk it's then put online for everyone to download you will have to wait I have zero control over googles process.
