### ISSUE TITLE
Auto rotation of the app resets the app to homescreen

### ISSUE THREAD

**Issue by Shah-do** [DonutWare/Fladder#174]
### Description

When playing a media and then turning your screen for rotation the media quits playing and the app goes to the app's home screen.
when forcing a media to play in rotated mode itself the app doesn't play the media and goes to home screen directly

### Reproduction steps

```bash
1. Go to 'a media'
2. Click on 'play'
3. turn phone
4. reach home page
```

### Screenshots

```bash

```

### Logs

```bash

```

### Platform

Android

### App Version

V0.5.0

**Comment by bazzadazza72** [comment]
I just tested this on iOS and it doesn't happen. Can anyone else test this for us?

**Comment by PartyDonut** [comment]
Unable to reproduce here as wel on Android and version 0.5.1

@Shah-do Can you provide a video of the exact steps to reproduce this behaviour. Also include the backend and rotation settings if possible.

**Comment by Shah-do** [comment]
Yes sure
https://streamable.com/28aple As you can see the video is playing in the background as we can hear the audio of the same.
https://streamable.com/u65qw1 it happens when not playing anything either

**Comment by PartyDonut** [comment]
@Shah-do Thanks for the video.

Could you tell me what device you're using. The problem that occurs is that your device is big enough (screen size) that it switches between phone/tablet mode. This causes the UI to rebuild in a strange way.

The reason for the video still playing is because it doesn't actually close the player it just removes the view of that player.

This is something I would need to fix but knowing the device would help me out testing it.

**Comment by Shah-do** [comment]
It's a Poco X3 Pro, with a 6.67-inch display

**Comment by Shah-do** [comment]
Ok I got to the bottom of the issue; my phone is quite big but I also at the same time I have my display size set to small. when I set the display size to default it seems to be working as intended. I hope this info helps better in fixing the bug.

**Comment by stanol** [comment]
I have the same problem. Display specs: Size 6.5 inches; Resolution 1080 x 2400 pixels, 20:9 ratio.

**Comment by Shah-do** [comment]
> I have the same problem. Display specs: Size 6.5 inches; Resolution 1080 x 2400 pixels, 20:9 ratio.

can you tell me are you also using your phone with the display size set to smaller than default and if the app works well with default display size

**Comment by stanol** [comment]
> > I have the same problem. Display specs: Size 6.5 inches; Resolution 1080 x 2400 pixels, 20:9 ratio.
> 
> can you tell me are you also using your phone with the display size set to smaller than default and if the app works well with default display size

I have the default screen settings. I tried to change the screen scale from 2 (default) to 3 (the elements on the screen became larger) and with these settings the player works fine.

**Comment by Shah-do** [comment]
> > > I have the same problem. Display specs: Size 6.5 inches; Resolution 1080 x 2400 pixels, 20:9 ratio.
> > 
> > 
> > can you tell me are you also using your phone with the display size set to smaller than default and if the app works well with default display size
> 
> I have the default screen settings. I tried to change the screen scale from 2 (default) to 3 (the elements on the screen became larger) and with these settings the player works fine.

Seems like the issue is with scaling then, the app assumes our device to be a tab depending on scale

**Comment by PartyDonut** [comment]
Thanks everyone for all the info.

For the curious people, a slightly more detailed explenation on why this happens.

Fladder checks your device width/height and compares them to a set of standardized range of values. 
From these values two things are calculated the layout (phone,tablet,desktop). And the ScreenLayout (Single,Dual).

For the layout this switching is preferred and also doesn't cause any side effects. However for the ScreenLayout this switches the screen from a single view to nested views (mostly on desktop and bigger tablets).

Some phones are appearently just in between these 2 positions.

It might require a bit more in the way of a re-work but #191 should atleast fix the player disappearing and the home-screen resetting.
