### ISSUE TITLE
🐛 No video when next episode starts playing from "Next-Up" section

### ISSUE THREAD

**Issue by Aadityajoshi151** [DonutWare/Fladder#176]
### Description

When the next episode is played from the "Next-Up" section (see screenshot attached), there isn't any video. There is just a blank screen while just the audio plays. This happens in both of the following cases:
- The next episode starts playing when the countdown finishes
- The user manually clicks the next episode button on this screen

### Reproduction steps

1. Watch an episode till the end and wait for the "Next Up" screen to show up.
2. Either wait for the countdown to finish OR simply click the next button present on the left side.
3. The next episode will start playing but only the audio will be heard on a blank screen. There won't be any video.

It is worth noting that the same episode when played through conventional methods (not from the next up screen) works fine.

![Image](https://github.com/user-attachments/assets/6a7f5cf6-7e85-44c9-ad2a-f469b8d6e2aa)

### Logs

```bash

```

### Platform

Linux

### App Version

v0.4.4 (1)

**Comment by PartyDonut** [comment]
This was resolved in #39 try out version 0.5 or higher. If not let me know in this issue.
