### ISSUE TITLE
🐛 Server discovery does not work on Web

### ISSUE THREAD

**Issue by PartyDonut** [DonutWare/Fladder#19]
### Description

Could be that Web just doesn't support this. Might have to be removed on Web all together.

### Reproduction steps

```bash
1. Open login page server discovery does not work.
```

### Platform

Web

### App Version

0.2.4

**Comment by DenixJG** [comment]
I've been reviewing the issue, and it seems the lack of support for server discovery on web, as they don't allow direct `UDP` broadcasts like other platforms. Possible solutions include:

1. Implementing **WebRTC** with a signaling server for peer-to-peer connections.
2. Creating a **backend service** to handle server discovery and expose it via a REST API.
3. For the moment use the default ports 

However, it seems quite challenging to achieve this directly on web without relying on some external service/app. I really think the solution 1 and 2 is not really the goal here.

**Comment by PartyDonut** [comment]
Best to remove the discovery part for web then.

I've been working on a docker container and implemented a config.json where you can configure the default server url that the front-end uses. 

This would give users the option to define a static url that the front-end always connects to (like the default jellyfin front-end).
