### ISSUE TITLE
💡 Screen Rotate

### ISSUE THREAD

**Issue by izakhearn** [DonutWare/Fladder#20]
### Summary

I recommend adding a button for screen rotation as very often I have my screen rotation locked to portaint but when I full screen it goes automatically to landscape on most apps. 

If you could add it that would be great

### Basic Example

Landscape rotation button.

### Drawbacks

Could be hard to implement.

**Comment by PartyDonut** [comment]
Hi, just to make sure we are on the same page.
You would like a option for the videoplayer to always start in a certain mode even if your device is locked in portrait mode?

For instance these options.

Videoplayer orientation:
* Landscape
* Portrait
* Device (Auto)

**Comment by izakhearn** [comment]
Yes that is correct. Just a button to manually rotate the view from either mode.
