### ISSUE TITLE
🐛 [iOS] Padding issues in videoplayer, possibly in more areas

### ISSUE THREAD

**Issue by krinkuto11** [DonutWare/Fladder#29]
### Description

The iOS version of the app doesn't take into account the existance of the notch in the iPhones and the edge of the player gets covered by it, rendering that zone unusable.
Tested in an iPhone 11, iOS 17.6.1

### Reproduction steps

```bash
1. Open Fladder
2. Open film/tv show episode
3. Rotate screen
```

### Platform

iOS

### App Version

v0.2.5

**Comment by PartyDonut** [comment]
Thanks for reporting this, just had a look seems like padding is a bit more unforgiving on iOS. Especially when in landscape mode 

I'll change the ticket so we can check the padding on more occasions.
