### ISSUE TITLE
💡 Docker Support

### ISSUE THREAD

**Issue by 2IkHLHB** [DonutWare/Fladder#3]
### Summary

Docker Support

### Basic Example

Docker Support

### Drawbacks

None

**Comment by NovaCyntax** [comment]
Seconding this, would keep consistency across my existing frontends.

**Comment by nwithan8** [comment]
Can you add a `latest` tag to your Docker releases, as is the standard for pulling the latest/most-recent image?

**Comment by PartyDonut** [comment]
Yes absolutely, just added it 👍🏼.
