### ISSUE TITLE
[NOTICE] Unraid app available

### ISSUE THREAD

**Issue by nwithan8** [DonutWare/Fladder#33]
Hey there, thanks for the great application and keeping Jellyfin development alive!

Now that you've released an official Docker image, I went ahead and made an Unraid app template so Unraid users can easily install Fladder on their systems. The app should be available in the Unraid Community Apps store in ~2 hours.

**Comment by PartyDonut** [comment]
Thanks 👍🏼 , looks like unraid uses a xml hosted somewhere is that something that would need to be in this repo?

**Comment by nwithan8** [comment]
It pulls from my template repo: https://github.com/nwithan8/unraid_templates/blob/main/templates/fladder.xml
