### ISSUE TITLE
🐛 AltStore invalid JSON error

### ISSUE THREAD

**Issue by krinkuto11** [DonutWare/Fladder#35]
### Description

After trying to add the AltStore repo, this error is shown: 'The given data was not valid JSON'

### Reproduction steps

1. Open AltStore
2. Go to Sources
3. Tap '+'
4. Enter 'https://github.com/DonutWare/Fladder/blob/develop/altstore.json'

### Platform

iOS

### App Version

v0.2.6

**Comment by PartyDonut** [comment]
Hi, I think you might have to use this url https://raw.githubusercontent.com/DonutWare/Fladder/refs/heads/develop/altstore.json.
The url you provided links to the github page

**Comment by krinkuto11** [comment]
Apologies, just noticed.
