### ISSUE TITLE
🐛 Error installing on Altstore _assert() error

### ISSUE THREAD

**Issue by swiipius** [DonutWare/Fladder#36]
### Description

Hello, 

I have tried to install Fladder using Altstore. 
First by using the ipa in the release and then with the source repo. Each time ending with the same error.

I am running on an iPhone 11 with iOS 18.1 beta

In the source the version is listed as v0.2.5 and the ipa is v0.2.6

(Btw love the project <3)

### Reproduction steps

1. Go to 'Release'
2. Click on 'download IPA'
3. Open 'Altstore'
4. Click on '+'
5. Upload the IPA
or
1. Open 'Altstore'
2. Go to 'sources'
3. Paste the link given in [#35](https://github.com/DonutWare/Fladder/issues/35)
4. Install 'Fladder'

### Logs

ldid.cpp(1461): _assert(): end >= size - 0x10

### Platform

iOS

### App Version

v0.2.6

**Comment by bazzadazza72** [comment]
This is the same issue I'm having, sorry I didn't mention it in my AltStore PR @PartyDonut.

I believe it's due to the IPA not being signed and AltStore having issues. I tried with a different unsigned IPA (Spotube) and that failed to install as well.

**Comment by krinkuto11** [comment]
I'm having the same issue. For now you can use Sideloadly to install it on an iPhone.

**Comment by PartyDonut** [comment]
Normally altStore would be the one to sign the .ipa correct? Difficult to test for me given I don't own an iPhone.
I will comment out the altStore link for now as to not cause confusion.

If any of you could take a look that would be greatly appreciated. 😃

**Comment by krinkuto11** [comment]
Apparently it needs something else. This issue still seems unresolved on other apps, this user talks about it pretty thouroughly: [link](https://github.com/altstoreio/AltStore/issues/1034#issuecomment-1998081907)

**Comment by PartyDonut** [comment]
One [work-around](https://github.com/altstoreio/AltStore/issues/170) seems to be to use Sideloadly and quickly transfer over the signed ipa.

**Comment by krinkuto11** [comment]
Yeah, that's gonna be difficult to automate. I'm guessing something could be jerry-rigged but it's gonna be limited by the weekly restriction.

**Comment by bazzadazza72** [comment]
> I'm having the same issue. For now you can use Sideloadly to install it on an iPhone.

I'll get some docs done up over the next couple days. At least there's a workaround and we're not stumping anyone.

> Normally altStore would be the one to sign the .ipa correct? Difficult to test for me given I don't own an iPhone.
> I will comment out the altStore link for now as to not cause confusion.
> 
> If any of you could take a look that would be greatly appreciated. 😃 

I'm not too conversed with it either, but I would assume it's signed when it's built, ready to be submitted to the App Store. I could be very wrong though, feel free to correct me.

**Comment by PartyDonut** [comment]
> Yeah, that's gonna be difficult to automate. I'm guessing something could be jerry-rigged but it's gonna be limited by the weekly restriction.

Yes, way more work and no way to automate it makes it a no go.

Someone mentioned SideStore #40 does that work with unsigned .ipa's? Or is it better to just advice people to use SideLoadly?

**Comment by bazzadazza72** [comment]
> Someone mentioned SideStore #40 does that work with unsigned .ipa's? Or is it better to just advise people to use SideLoadly?

I'm not sure, I can test it if you like. If there's no change, it'd be best to advise people to use Sideloadly.

**Comment by krinkuto11** [comment]
> > Yeah, that's gonna be difficult to automate. I'm guessing something could be jerry-rigged but it's gonna be limited by the weekly restriction.
> 
> Yes, way more work and no way to automate it makes it a no go.
> 
> Someone mentioned SideStore [#40](https://github.com/DonutWare/Fladder/issues/40) does that work with unsigned .ipa's? Or is it better to just advice people to use SideLoadly?

I'm gonna try and do some research but can't make any assurances. I found [fastlane](https://docs.fastlane.tools/actions/sigh/) promising but it's gonna require some work alongside XCode CLI.

**Comment by 25Braeden** [comment]
Hey @PartyDonut, I know this is closed, but I actually found a way to get the IPA installing through AltStore without the `ldid.cpp(1461)` crash. 

The error triggers because AltStore's `ldid` fails when it encounters completely unsigned inner Flutter frameworks. If a dummy ad-hoc signature is applied to the inner frameworks and the outer app shell *before* packaging the IPA, AltStore can successfully read the binary and overwrite it with a real Apple ID signature.

Here are the commands I ran locally on the extracted payload to fix it:
```bash
# Strip out broken/partial signatures
rm -rf Payload/Runner.app/_CodeSignature
rm -rf Payload/Runner.app/Frameworks/*/_CodeSignature

# Ad-hoc sign the inner Flutter frameworks
codesign -s - -f Payload/Runner.app/Frameworks/*

# Ad-hoc sign the main app shell
codesign -s - -f Payload/Runner.app
```

If these `codesign` steps are added to the release workflow right before the final `zip` packaging step, the release IPAs should be fully compatible with AltStore straight out of the box!
