### ISSUE TITLE
🐛 [Desktop/Linux] Blackscreen when opening video in same player instance aka when pressing the next button

### ISSUE THREAD

**Issue by tam1m** [DonutWare/Fladder#39]
### Description

This issue occurs on Linux (I haven't tested other desktop platforms) with mpv v0.39.0. 

I tried building the app with media_kit from the main branch and could not reproduce anymore. After disecting, I found that this [PR](https://github.com/media-kit/media-kit/pull/815) / [commit](https://github.com/media-kit/media-kit/commit/3da3f3ddfa0730c3cd5a990c93a4fd47fe94533c) in media_kit resolves the issue. However, the problem is that this hasn't been included in any release yet. Relying on the main branch would  probably not be ideal. So not sure how to handle this.

For now I just patched pubspec.yaml to pull the media_kit deps from the git main branch. 

If anyone wants to test:

pubspec.patch 
```
--- pubspec.yaml	2024-10-16 14:53:52.186901124 +0200
+++ pubspec.yaml.new	2024-10-16 14:54:19.030288511 +0200
@@ -27,6 +27,14 @@
 # dependencies can be manually updated by changing the version numbers below to
 # the latest version available on pub.dev. To see which dependencies have newer
 # versions available, run `flutter pub outdated`.
+dependency_overrides:
+  media_kit:
+    git:
+      # path: ./media_kit/media_kit
+      url: https://github.com/alexmercerind/media_kit.git
+      path: media_kit
+      ref: main
+
 dependencies:
   flutter:
     sdk: flutter
@@ -68,9 +76,30 @@
   google_fonts: ^6.1.0
 
   # Media
-  media_kit: ^1.1.10 # Primary package.
-  media_kit_video: ^1.2.4 # For video rendering.
-  media_kit_libs_video: ^1.0.4 # Native video dependencies.
+  # media_kit: ^1.1.10 # Primary package.
+  # media_kit_video: ^1.2.4 # For video rendering.
+  # media_kit_libs_video: ^1.0.4 # Native video dependencies.
+  # Primary package
+  media_kit:
+    git:
+      url: https://github.com/alexmercerind/media_kit.git
+      path: media_kit
+      ref: main
+
+  # For video rendering
+  media_kit_video:
+    git:
+      url: https://github.com/alexmercerind/media_kit.git
+      path: media_kit_video
+      ref: main
+
+  # # Native video dependencies
+  media_kit_libs_video:
+    git:
+      url: https://github.com/alexmercerind/media_kit.git
+      path: libs/universal/media_kit_libs_video
+      ref: main
+
   audio_service: ^0.18.12
 
   # UI Components
```

### Reproduction steps

Steps to reproduce:
1. play episode
2. press next to skip to next episode
3. audio will play with just a blackscreen

### Platform

Linux

**Comment by PartyDonut** [comment]
Thanks for reporting the bug and also testing out a solution!

You're right using the git repo's main branch to build of could cause more issues. One other solution might be to create fork and apply just that fix for now. I will have a look into the options 👍🏼

**Comment by PartyDonut** [comment]
I'm moving this to #122 so I can keep track of issue relating the the media player being used in Fladder.
