### ISSUE TITLE
need this feature: add to favorites when playing

### ISSUE THREAD

**Issue by myrshfrs** [DonutWare/Fladder#46]
### Summary

It would be very convenient if there was a favorites button when playing the video.

### Basic Example

Add a favorites button below the player

### Drawbacks

no

**Comment by PartyDonut** [comment]
Do I have good news for you 😄 .

When playing a video tap the menu button, this wil open video player settings.  
From there you can press the title of whatever you're watching, and there are a few options. One of them is "Add to favourites"
