### ISSUE TITLE
💡Retain selected filters in libraries

### ISSUE THREAD

**Issue by civilblur** [DonutWare/Fladder#52]
### Summary

Keep the selected filters for the individual library in order to retain the same view when re-entering the library.

Would be a great quality of life-feature, as one would be able to create their own view for each specific library, opposed to having to filter and sort every time when entering the respective library.

### Basic Example

1. Enter a library, e.g. "Movies".
2. Adjust filter: "Sort by: Release date", "Sort order: Descending".
3. Return to dashboard.
4. Go to library "Movies". Filter from before (Release date, Descending) are automatically selected as default values.

5. Enter library "Series".
6. No specific filters are applied, as the filter are not affected by the filter from "Movies" library.
7. Adjust filter: "Genre: Action", "Group by: Rating".
8. Return to dashboard.
9. Go to library "Series": Filter from before (Action, Rating) are automatically selected as default values.

10. When re-entering "Movies", default filter is "Release date, Descending". For "Series", default filter is "Action, Rating".

### Drawbacks

For those who do not wish to retain the filter values, they would need to clear the filter every time. A setting to enable/disable this could potentially be a way to solve it?

**Comment by PartyDonut** [comment]
Hi, good idea.

The default behaviour should probably still be nothing selected. 
For instance tapping the recently added titles also sets parameters to show library sorted by recently added.

A better option could be allowing you to save filters per library, and then have you select a favourite. That get's loaded whenever no other settings are incoming. Like in the case of recently added.

**Comment by civilblur** [comment]
> Hi, good idea.
> 
> The default behaviour should probably still be the default filters like now. For instance tapping the recently added titles also sets parameters to show library sorted by recently added.
> 
> A better option could be allowing you to save filters per library, and then have you select a favourite. That get's loaded whenever no other settings are incoming. Like in the case of recently added.

Thanks for taking a stab at this, I think your suggestion will achieve the the desired result!

Out of curiosity, if Fladder is running on docker, would these "favorite" filers be persistent between all web sessions on the same Jellyfin login?

**Comment by PartyDonut** [comment]
Sorry for the late response.

The settings would be saved on a browser basis. They would be saved in the cookies for that webpage. No way to save this to the jellyfin-server itself unfortunately.

**Comment by civilblur** [comment]
No worries, and that makes sense. I was primarily curious as I didn't see any persistent storage documented anywhere.
