### ISSUE TITLE
🐛 Missing Shared Library on Fedora 40

### ISSUE THREAD

**Issue by Nanianmichaels** [DonutWare/Fladder#53]
### Description

Hello.

I have just run Fladder on Fedora 40, and it errored out with a missing shared library, more specifically libmpv.so.1.

Please consider adding that library to the app's lib folder, or adding instructions on how to get it on the system on the download page (included below for F40).

### Reproduction steps

1. Try to load the app via terminal.
2. App will error out from missing shared library; if loaded by double-clicking the executable, it will simply not load.

For F40 users, you need to install at least mpv-devel, and then symlink the shared library.

Steps required:

- sudo dnf install mpv-devel
- sudo ln -s /usr/lib64/libmpv.so /usr/lib64/libmpv.so.1

I personally also installed mpv, but the library in question was only available on mpv-devel.

For Debian-based systems, the commands apparently are:
sudo apt install libmpv-dev libmpv2 (or libmpv1, depending on the source)
sudo ln -s /usr/lib/x86_64-linux-gnu/libmpv.so /usr/lib/libmpv.so.1

I have not, however, tested the solution on a Debian-based system.

### Platform

Linux

### App Version

v0.2.6-alpha

**Comment by bazzadazza72** [comment]
> I have not, however, tested the solution on a Debian-based system.

I believe the issue happens on all Linux distributions, including Debian. I'll have a look at what modules it uses, could be a typo somewhere.

**Comment by bazzadazza72** [comment]
If I can't fix the issue, or another workaround other than the one you've provided is found, I'll write some documentation

**Comment by PartyDonut** [comment]
I think it would also help if we can package the linux binaries in something like Flatpak or an appimage (or both)?

That would include all libraries I believe.

**Comment by bazzadazza72** [comment]
I did think about doing that, I would recommend doing an AppImage, personally, but if you want to distribute it to a wider audience, Flatpak would be the way to go.

**Comment by PartyDonut** [comment]
Let's try for both if possible 👍🏼 .

**Comment by bazzadazza72** [comment]
Just found this as a resource: https://appimage-builder.readthedocs.io/en/latest/examples/flutter.html, very promising

**Comment by bazzadazza72** [comment]
> Let's try for both if possible

Will get started on that this week, shouldn't take too long 🤞

**Comment by lmgarret** [comment]
I'm working on a Flatpak build [here](https://github.com/lmgarret/Fladder/tree/lmg/flatpak) , I'm getting close to something clean for a PR. 

If anyone's impatient or curious, you can already grab the flatpak in the [generated artifacts here](https://github.com/lmgarret/Fladder/actions/runs/11669830908). I've successfully tested it on the Steam Deck, which is honestly my main motivation for this!

**Comment by bazzadazza72** [comment]
Thanks a lot @lmgarret for picking up the slack. I'd be happy to test the Flatpak on my machines, I'll let you know if I have any hiccups.

**Comment by bazzadazza72** [comment]
I'd like to apologise to @PartyDonut for both not contributing and going radio silence. I've lost motivation from losing two of my desktop's storage drives, including my Jellyfin server.

If you'd like me to work on any outstanding issues, I'd be more than happy to regain my motivation and make the damned best Jellyfin app there is.

**Comment by PartyDonut** [comment]
> I'd like to apologise to @PartyDonut for both not contributing and going radio silence. I've lost motivation from losing two of my desktop's storage drives, including my Jellyfin server.
> 
> If you'd like me to work on any outstanding issues, I'd be more than happy to regain my motivation and make the damned best Jellyfin app there is.

Hey thats perfectly fine theres no rush 👍.
Working on this project should always be whenever or even if you feel like working on it, no pressure 😀.

Sorry to hear about losing the storage drives. If you want to pick up any issue you're more then welcome.

**Comment by PartyDonut** [comment]
Closing this as both #125 and #141 help/resolve this
