### ISSUE TITLE
🐛 No visible text when external font file is unreachable, no local fallback font available

### ISSUE THREAD

**Issue by civilblur** [DonutWare/Fladder#54]
### Description

When Google Fonts is unreachable (or blocked on browser/DNS level), there is no font to fallback to. This results in a UI with no visible text.

After user has logged in, the font file will endlessly try to be fetched at `https://fonts.gstatic.com/s/notosanssc/...`, which significantly slows down the app's performance. The endless request for a font file doesn't happen on the login page, however.

Ideally, it would be great if all font files could be local and not rely on external services. Alternatively, set a fallback font to `FladderTheme` to use a web-safe font (like sans-serif, arial, etc.).

I wasn't completely sure if I should have categorized the issue under "Bug report" or not, as this situation is a result of my setup artificially blocking Google Fonts for FOSS reasons. But this could still happen if the external font service is down/slow.

### Reproduction steps

For testing purpose, the scenario can be reproduced by using uBlock Origin to block requests:

1. Install uBlock Origin extension on a browser that supports Manifest V2 (e.g. Firefox).
2. Under settings, go to the tab "My filters".
3. Add the following to the text area to block the relevant requests:
```
||https://fonts.google.com^
||fonts.gstatic.com^$important
||fonts.googleapis.com^$important
```

### Platform

Web

### App Version

v0.2.6

**Comment by PartyDonut** [comment]
Thanks for reminding me I was meaning to remove the google fonts dependancy 😃.
