### ISSUE TITLE
💡 Use `Authorization` header to send access token to API

### ISSUE THREAD

**Issue by laurentlbm** [DonutWare/Fladder#61]
### Summary

Currently, [the code](https://github.com/DonutWare/Fladder/blob/d572884e61e5bb0babc721242d002158afb16564/lib/models/credentials_model.dart#L30) sends the access token using the deprecated `X-Emby-Token` header and sends additional details in the `X-Emby-Authorization` header. It would be better to combine both and use the `Authorization` header as described here: https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f#sending-authorization-values

The reason that I ask is because I use [JellySearch](https://gitlab.com/DomiStyle/jellysearch/) and it doesn't support the `X-Emby-Token` header. JellySearch is a container that indexes Jellyfin media to provide a more powerful search. Using a reverse proxy, JellySearch can transparently replace Jellyfin's search endpoints, improving the search results for all clients (web, android tv, official android app, findroid, streamyfin). In Fladder, the search unfortunately fails because JellySearch [only checks certain auth headers](https://gitlab.com/DomiStyle/jellysearch/-/blob/main/src/JellySearch/Controllers/SearchController.cs?ref_type=heads#L46). We could submit a bug report on their repository asking to add support for the `X-Emby-Token` header, but since it's deprecated, it might be better to simply make the change here.

### Basic Example

Unless the logic is duplicated elsewhere, the change is simple:
```
      'authorization':
          'MediaBrowser Token="${token}", Client="${application.name}", Device="${application.os}", DeviceId="$deviceId", Version="${application.version}"'
```

### Drawbacks

None AFAIK.

**Comment by PartyDonut** [comment]
@laurentlbm Fixed! Thanks for the heads-up 👍🏼
