### ISSUE TITLE
💡 Allow setting default server

### ISSUE THREAD

**Issue by sjorge** [DonutWare/Fladder#64]
### Summary

The web experience is actually pretty cool! It looks more modern than the build in webui and works way better than the vue one. I currently run a copy under the /fladder URL on my server, it would be nice to be able to set a default, or even to lock the server.

### Basic Example

Unpack web client, edit config to set default server. Visit URL and have it just prompt for a user/pass.

### Drawbacks

Potentially pinned to one server, but that might actually be desirable when hosting it on the same server as jellyfin itself.

**Comment by PartyDonut** [comment]
Hi, this is already implemented in the current web version. It was added in #32.

For docker it's pretty easy you can check the docker-compose.yml in the git repo. If you host the web folder yourself you can change the baseUrl in \assets\config\config.json.

**Comment by akash-258** [comment]
@PartyDonut Can you tell me how can I connect to the internal jellyfin docker ip ?

I have both jellyfin server and fladder running inside containers, but want to set the baseUrl to that of the jellyfin container. I want this so I can just access fladder through either local address, over a vpn like tailscale or over public internet and I won't have to enter any server url inside fladder.
