### ISSUE TITLE
🐛 The title of the audio selector popup is wrong?

### ISSUE THREAD

**Issue by kaiiiz** [DonutWare/Fladder#77]
### Description

Hello,

I think the title of the audio selector popup should be "Audio" instead of "Subtitles"?

BTW, thanks for building this wonderful apps!

### Reproduction steps

1. Open any videos
2. Click on audio selection button
3. See error

### Screenshots

![Image](https://github.com/user-attachments/assets/1e9eb549-6ed7-433f-ab26-4604884c19d2)

![Image](https://github.com/user-attachments/assets/4f8b5b09-58b8-4870-94cd-8cdd549839de)

### Platform

Android, Windows

### App Version

v0.3.0-alpha

**Comment by PartyDonut** [comment]
Oeps, thanks for letting me know. Fixed
